### ISSUE TITLE
lowercase errors key in the json response

### ISSUE THREAD

**Issue by kallusakar** [ddymko/go-jsonerror#5]
Hi, 
thanks for the library, it works great but I was wondering if the "Errors" key in the response shouldn't be lowercase, as that is how json api spec is showing it - https://jsonapi.org/format/1.1/#error-objects 

It would probably be a breaking change for existing projects so I'm writing it here first but I'd be happy to post a pull request fixing it.

Best Regard,
Lukas.

**Comment by ddymko** [comment]
@kallusakar I am sorry for the long reply. I completely missed this...sorry about that. Errors is capitalized so it is an exported field in the struct. However, we should add a tag to be safe so the encoder always sets it to lower case.

Feel free to submit a pull request to address this issue!
